# docker-compose.yml

services:
  app:
    container_name: django-container
    build:
      context: .
    restart: always
    volumes:
      - static-data:/app/staticfiles
      - database:/app/database

  proxy:
    container_name: nginx-container
    build:
      context: ./proxy/initiate
    restart: unless-stopped
    volumes:
      - static-data:/app/staticfiles
      - database:/app/database
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-container
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    depends_on:
      - proxy

volumes:
  static-data:
  database:
