# Generated by Django 5.1 on 2024-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventoryinspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryinspection",
            name="inventory_adjusted",
            field=models.BooleanField(default=False, verbose_name="在庫調整済み"),
        ),
    ]
