# Generated by Django 5.1 on 2024-08-25 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventoryinspection_inventory_adjusted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryinspection",
            options={"ordering": ("id",)},
        ),
    ]
