# Generated by Django 5.1 on 2024-08-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_site_latitude_site_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="自動追加",
                max_digits=9,
                null=True,
                verbose_name="緯度",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="自動追加",
                max_digits=9,
                null=True,
                verbose_name="経度",
            ),
        ),
    ]
