# Generated by Django 5.1.1 on 2024-09-15 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_site_latitude_alter_site_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DrugObsoleteBySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_obsolete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='最終更新日時')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obsolete_status', to='inventory.drug')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'unique_together': {('drug', 'site')},
            },
        ),
    ]
