# Generated by Django 5.1.1 on 2024-09-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_userprofile_user_drugobsoletebysite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugobsoletebysite',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='drugobsoletebysite',
            name='user',
        ),
    ]
