# Generated by Django 5.1.1 on 2024-09-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_drugobsoletebysite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='obsoleted',
            field=models.BooleanField(default=False, help_text='廃止された項目は、システムから削除されるわけではありませんが、一般的な操作や検索の対象からは除外されます。', verbose_name='全院で廃止する'),
        ),
    ]
