# Generated by Django 5.1.1 on 2024-09-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_drug_obsoleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugobsoletebysite',
            options={'ordering': ('drug', 'site')},
        ),
    ]
