# Generated by Django 5.1.1 on 2024-09-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_drugobsoletebysite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugobsoletebysite',
            options={'ordering': ('drug', 'site'), 'verbose_name': 'Drug Obsolete Status by Site', 'verbose_name_plural': 'Drug Obsolete Statuses by Site'},
        ),
        migrations.AlterField(
            model_name='drugobsoletebysite',
            name='is_obsolete',
            field=models.BooleanField(default=False, verbose_name='廃止する'),
        ),
    ]
